<table>
  <tr>
    <th colspan="2" rowspan="3">Lift<br>Point<br>Height<br>(m)</th>
    <th colspan="4">Lifting Capacity<br>Over-Front<br>Blade Down<br><br>unit=ton</th>
    <th colspan="4">Lifting Capacity<br>Over-Front<br>Blade Up<br><br>unit=ton</th>
    <th colspan="4">Lifting Capacity<br>Over-Side<br><br>unit=ton</th>
  </tr>
  <tr>
  </tr>
  <tr>
    <td colspan="4">Lift Point Radius (m)</td>
    <td colspan="4">Lift Point Radius (m)</td>
    <td colspan="4">Lift Point Radius (m)</td>
  </tr>
  <tr>
    <td>1.2</td>
    <td>1.8</td>
    <td>2.5</td>
    <td>MAX</td>
    <td>1.2</td>
    <td>1.8</td>
    <td>2.5</td>
    <td>MAX</td>
    <td>1.2</td>
    <td>1.8</td>
    <td>2.5</td>
    <td>MAX</td>
  </tr>
  <tr>
    <td rowspan="4">GL</td>
    <td>1.8</td>
    <td>-</td>
    <td>0.20</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>0.20</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>0.17</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <td>1.2</td>
    <td>-</td>
    <td>0.23</td>
    <td>0.21</td>
    <td>0.20</td>
    <td>-</td>
    <td>0.21</td>
    <td>0.13</td>
    <td>0.12</td>
    <td>-</td>
    <td>0.17</td>
    <td>0.10</td>
    <td>0.10</td>
  </tr>
  <tr>
    <td>0.6</td>
    <td>0.54</td>
    <td>0.30</td>
    <td>0.21</td>
    <td>0.19</td>
    <td>0.36</td>
    <td>0.19</td>
    <td>0.13</td>
    <td>0.11</td>
    <td>0.28</td>
    <td>0.16</td>
    <td>0.10</td>
    <td>0.09</td>
  </tr>
  <tr>
    <td>0</td>
    <td>0.55</td>
    <td>0.31</td>
    <td>0.19</td>
    <td>0.17</td>
    <td>0.32</td>
    <td>0.18</td>
    <td>0.12</td>
    <td>0.11</td>
    <td>0.25</td>
    <td>0.14</td>
    <td>0.10</td>
    <td>0.09</td>
  </tr>
</table>